<table>
	<tr>
		<td>tBodyAcc-mean()-X</td>
		<td>tBodyAcc-mean()-Y</td>
		<td>tBodyAcc-mean()-Z</td>
		<td>tBodyAcc-std()-X</td>
		<td>tBodyAcc-std()-Y</td>
		<td>tBodyAcc-std()-Z</td>
		<td>tGravityAcc-mean()-X</td>
		<td>tGravityAcc-mean()-Y</td>
		<td>tGravityAcc-mean()-Z</td>
		<td>tGravityAcc-std()-X</td>
		<td>tGravityAcc-std()-Y</td>
		<td>tGravityAcc-std()-Z</td>
		<td>tBodyAccJerk-mean()-X</td>
		<td>tBodyAccJerk-mean()-Y</td>
		<td>tBodyAccJerk-mean()-Z</td>
		<td>tBodyAccJerk-std()-X</td>
		<td>tBodyAccJerk-std()-Y</td>
		<td>tBodyAccJerk-std()-Z</td>
		<td>tBodyGyro-mean()-X</td>
		<td>tBodyGyro-mean()-Y</td>
		<td>tBodyGyro-mean()-Z</td>
		<td>tBodyGyro-std()-X</td>
		<td>tBodyGyro-std()-Y</td>
		<td>tBodyGyro-std()-Z</td>
		<td>tBodyGyroJerk-mean()-X</td>
		<td>tBodyGyroJerk-mean()-Y</td>
		<td>tBodyGyroJerk-mean()-Z</td>
		<td>tBodyGyroJerk-std()-X</td>
		<td>tBodyGyroJerk-std()-Y</td>
		<td>tBodyGyroJerk-std()-Z</td>
		<td>tBodyAccMag-mean()</td>
		<td>tBodyAccMag-std()</td>
		<td>tGravityAccMag-mean()</td>
		<td>tGravityAccMag-std()</td>
		<td>tBodyAccJerkMag-mean()</td>
		<td>tBodyAccJerkMag-std()</td>
		<td>tBodyGyroMag-mean()</td>
		<td>tBodyGyroMag-std()</td>
		<td>tBodyGyroJerkMag-mean()</td>
		<td>tBodyGyroJerkMag-std()</td>
		<td>fBodyAcc-mean()-X</td>
		<td>fBodyAcc-mean()-Y</td>
		<td>fBodyAcc-mean()-Z</td>
		<td>fBodyAcc-std()-X</td>
		<td>fBodyAcc-std()-Y</td>
		<td>fBodyAcc-std()-Z</td>
		<td>fBodyAccJerk-mean()-X</td>
		<td>fBodyAccJerk-mean()-Y</td>
		<td>fBodyAccJerk-mean()-Z</td>
		<td>fBodyAccJerk-std()-X</td>
		<td>fBodyAccJerk-std()-Y</td>
		<td>fBodyAccJerk-std()-Z</td>
		<td>fBodyGyro-mean()-X</td>
		<td>fBodyGyro-mean()-Y</td>
		<td>fBodyGyro-mean()-Z</td>
		<td>fBodyGyro-std()-X</td>
		<td>fBodyGyro-std()-Y</td>
		<td>fBodyGyro-std()-Z</td>
		<td>fBodyAccMag-mean()</td>
		<td>fBodyAccMag-std()</td>
		<td>fBodyBodyAccJerkMag-mean()</td>
		<td>fBodyBodyAccJerkMag-std()</td>
		<td>fBodyBodyGyroMag-mean()</td>
		<td>fBodyBodyGyroMag-std()</td>
		<td>fBodyBodyGyroJerkMag-mean()</td>
		<td>fBodyBodyGyroJerkMag-std()</td>
	</tr>
</table>
